insert into channel (ID, CHANNEL_DISPLAY_NAME, CHANNEL_NAME, DESCRIPTION, LINK, STATUS, TIER, TYPE) values (1, 'CHANNEL_DISPLAY_NAME', 'CHANNEL_NAME', 'DESCRIPTION', 'LINK', 2, 2, 2);
insert into channel (ID, CHANNEL_DISPLAY_NAME, CHANNEL_NAME, DESCRIPTION, LINK, STATUS, TIER, TYPE) values (2, 'CHANNEL_DISPLAY_NAME', 'CHANNEL_NAME', 'DESCRIPTION', 'LINK', 2, 2, 2);

insert into sub_channel (ID, IGNORED, LINK, NUM_MESSAGES, NUM_TOPICS, TITLE, CHANNEL_ID) values (1, 4, 'link', 34, 23, 'title', 1);
insert into sub_channel (ID, IGNORED, LINK, NUM_MESSAGES, NUM_TOPICS, TITLE, CHANNEL_ID) values (2, 4, 'link', 34, 23, 'title', 2);

insert into topic (ID, FIRST_POST_ID, IGNORED, IS_RELEVANT, LANGUAGE, LAST_POST_ID, LINK, SUMMARY, TITLE, TRANSLATED_TITLE, CHANNEL_ID, SUB_CHANNEL_ID) values (1, 1, 4, 2, 'LANGUAGE' , 1, 'LINK', 'SUMMARY', 'TITLE', 'TRANSLATED_TITLE', 1, 1);
insert into topic (ID, FIRST_POST_ID, IGNORED, IS_RELEVANT, LANGUAGE, LAST_POST_ID, LINK, SUMMARY, TITLE, TRANSLATED_TITLE, CHANNEL_ID) values (2, 1, 4, 2, 'LANGUAGE2' , 1, 'LINK2', 'SUMMARY2', 'TITLE2', 'TRANSLATED_TITLE', 1);

insert into MESSAGE_HISTORY  (ID, MESSAGE_CONTENT, MESSAGE_CONTENT_RAW, MESSAGE_TITLE, POST_VERSION, PROCESSED, CHANNEL_ID) values (1, 'content', 'contentrow', 'title', 3, 4, 1);

insert into user(USER_ID, LINK, USER_ID_ON_CHANNEL, USER_NO_OF_POSTS, USER_PASSWORD_HASH, USER_PASSWORD_SALT, USER_WEBSITE, USERNAME ) values (1, 'link', '1', 20, 'hsh', 'slt', 'website', 'usernme');
insert into user(USER_ID, LINK, USER_ID_ON_CHANNEL, USER_NO_OF_POSTS, USER_PASSWORD_HASH, USER_PASSWORD_SALT, USER_WEBSITE, USERNAME ) values (2, 'link', '1', 20, 'hsh', 'slt', 'website', 'usernme');

insert into message (ID, MESSAGE_CONTENT, MESSAGE_CONTENT_AUTO_TRANSLATION, MESSAGE_CONTENT_MANUAL_TRANSLATION, MESSAGE_CONTENT_RAW, MESSAGE_TITLE,MESSAGE_TITLE_AUTO_TRANSLATION, MESSAGE_TITLE_MANUAL_TRANSLATION, POST_VERSION, PROCESSED, TRANSLATION_STATUS, TRANSLATION_STATUS_COMMENTARY, TOPIC_ID, USER_USER_ID) values (1, 'content', 'counter', 'mnul', 'row', 'title', ' titletrn', 'uto', 3, 2, 'ststus', 'commentry', 1, 1);

insert into USERIPADDRESS( ID , IP_ADDRESS, IP_ADDRESS_COUNTRY, IP_ADDRESS_PROVIDER, IP_ADDRESS_USE_DATE_TIME) values (1, '1452', 'sdf', 'hsh', 45);
